# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJssdbxYBluvPtxioJpupUZH3Q805Jzv
"""

pip install streamlit pandas matplotlib seaborn scikit-learn fpdf openpyxl xlsxwriter

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score
from sklearn.preprocessing import LabelEncoder
import numpy as np
from fpdf import FPDF
import io

st.set_page_config(page_title="📊 AI Визуализатор и ML Анализатор", layout="wide")
st.title("📊 AI-помощник для визуализации данных и ML с автоматическим отчётом")
st.markdown("Загрузите CSV, Excel или JSON — получите анализ, ML-прогнозирование и PDF-отчёт.")

def load_data(uploaded_file):
    try:
        if uploaded_file.name.endswith('.csv'):
            return pd.read_csv(uploaded_file)
        elif uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        elif uploaded_file.name.endswith('.json'):
            data = json.load(uploaded_file)
            if isinstance(data, list):
                return pd.DataFrame(data)
            else:
                st.error("JSON должен содержать массив объектов.")
                return None
    except Exception as e:
        st.error(f"Ошибка при загрузке файла: {e}")
        return None

def save_fig_to_buffer(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format='png')
    buf.seek(0)
    plt.close(fig)
    return buf

def generate_pdf_report(df, target, task, metrics, feature_importance, figs):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Отчёт по анализу и ML", ln=True, align='C')

    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(0, 10, f"Общее количество строк: {df.shape[0]}", ln=True)
    pdf.cell(0, 10, f"Общее количество столбцов: {df.shape[1]}", ln=True)
    pdf.cell(0, 10, f"Целевой столбец: {target}", ln=True)
    pdf.cell(0, 10, f"Тип задачи: {task}", ln=True)

    pdf.ln(10)
    pdf.cell(0, 10, "Метрики:", ln=True)
    for k, v in metrics.items():
        pdf.cell(0, 10, f"{k}: {v}", ln=True)

    pdf.ln(10)
    pdf.cell(0, 10, "Важность признаков:", ln=True)
    for feat, val in feature_importance.items():
        pdf.cell(0, 10, f"{feat}: {val:.3f}", ln=True)

    pdf.ln(10)
    for i, fig_buf in enumerate(figs):
        pdf.image(fig_buf, x=10, w=180)
        pdf.ln(85)

    return pdf.output(dest='S').encode('latin1')

def basic_ml_analysis(df):
    st.subheader("🤖 Автоматический ML-анализ")

    target = st.selectbox("Выберите целевой столбец (для ML анализа)", df.columns)
    if not target:
        return None

    X = df.drop(columns=[target])
    y = df[target]

    X_processed = X.copy()
    for col in X_processed.columns:
        if X_processed[col].dtype == 'object':
            X_processed[col] = X_processed[col].fillna('missing')
            le = LabelEncoder()
            X_processed[col] = le.fit_transform(X_processed[col])
        else:
            X_processed[col] = X_processed[col].fillna(X_processed[col].mean())

    if y.dtype == 'object':
        y = y.fillna('missing')
        le_target = LabelEncoder()
        y = le_target.fit_transform(y)
    else:
        y = y.fillna(y.mean())

    if len(np.unique(y)) <= 20 and y.dtype in [np.int64, np.int32, np.int16]:
        task = 'classification'
    elif y.dtype in [np.float64, np.float32]:
        task = 'regression'
    else:
        st.info("Целевой столбец имеет неподдерживаемый тип для ML анализа.")
        return None

    X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.3, random_state=42)

    figs = []
    metrics = {}
    feature_importance = {}

    if task == 'classification':
        st.write("Задача: Классификация")
        model = LogisticRegression(max_iter=1000)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        st.write(f"Accuracy на тесте: **{acc:.2f}**")
        metrics['Accuracy'] = f"{acc:.2f}"

        cm = confusion_matrix(y_test, y_pred)
        fig, ax = plt.subplots()
        sns.heatmap(cm, annot=True, fmt='d', ax=ax)
        ax.set_title("Confusion Matrix")
        st.pyplot(fig)
        figs.append(save_fig_to_buffer(fig))

        coef = pd.Series(model.coef_[0], index=X.columns)
        coef_abs = coef.abs().sort_values(ascending=False)
        st.write("Важность признаков (коэффициенты модели):")
        st.bar_chart(coef_abs)
        feature_importance = coef_abs.to_dict()

    elif task == 'regression':
        st.write("Задача: Регрессия")
        model = LinearRegression()
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        r2 = r2_score(y_test, y_pred)
        st.write(f"R² на тесте: **{r2:.2f}**")
        metrics['R²'] = f"{r2:.2f}"

        fig, ax = plt.subplots()
        ax.scatter(y_test, y_pred, alpha=0.5)
        ax.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
        ax.set_xlabel("Истинные значения")
        ax.set_ylabel("Предсказанные")
        ax.set_title("Сравнение истинных и предсказанных значений")
        st.pyplot(fig)
        figs.append(save_fig_to_buffer(fig))

        coef = pd.Series(model.coef_, index=X.columns)
        coef_abs = coef.abs().sort_values(ascending=False)
        st.write("Важность признаков (коэффициенты модели):")
        st.bar_chart(coef_abs)
        feature_importance = coef_abs.to_dict()

    if st.button("📄 Сгенерировать PDF-отчёт"):
        pdf_bytes = generate_pdf_report(df, target, task, metrics, feature_importance, figs)
        st.download_button("Скачать отчёт", pdf_bytes, file_name="report.pdf", mime="application/pdf")

    return None

st.write("### Загрузка данных")
uploaded_file = st.file_uploader("Загрузите файл", type=["csv", "xlsx", "xls", "json"])

if uploaded_file:
    df = load_data(uploaded_file)

    if df is not None:
        st.subheader("🔍 Общая информация")
        st.write(f"Строк: {df.shape[0]}, Колонок: {df.shape[1]}")

        tab1, tab2, tab3, tab4 = st.tabs(["Данные", "Статистика", "Визуализация", "ML Анализ"])

        with tab1:
            st.dataframe(df.head())

        with tab2:
            st.write("Типы данных:")
            st.write(df.dtypes)
            st.write("Пропущенные значения:")
            st.write(df.isnull().sum())

        with tab3:
            num_cols = df.select_dtypes(include=["number"]).columns
            if len(num_cols) > 0:
                selected_num = st.selectbox("Выберите числовую колонку", num_cols)
                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
                sns.histplot(df[selected_num], ax=ax1, kde=True)
                sns.boxplot(x=df[selected_num], ax=ax2)
                st.pyplot(fig)

            cat_cols = df.select_dtypes(include=["object", "category"]).columns
            if len(cat_cols) > 0:
                selected_cat = st.selectbox("Выберите категориальную колонку", cat_cols)
                fig, ax = plt.subplots()
                df[selected_cat].value_counts().plot(kind='bar', ax=ax)
                st.pyplot(fig)

        with tab4:
            basic_ml_analysis(df)
else:
    st.info("Пожалуйста, загрузите файл для анализа и ML")