# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJssdbxYBluvPtxioJpupUZH3Q805Jzv
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from fpdf import FPDF
import io

st.set_page_config(page_title="📊 AI Визуализатор Данных", layout="wide")
st.title("📊 AI-помощник для визуализации и анализа данных")

st.markdown("Загрузите CSV, Excel или JSON файл, получите визуализацию и ML-анализ 📈")


def load_data(uploaded_file):
    try:
        if uploaded_file.name.endswith('.csv'):
            return pd.read_csv(uploaded_file)
        elif uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        elif uploaded_file.name.endswith('.json'):
            data = json.load(uploaded_file)
            if isinstance(data, list):
                return pd.DataFrame(data)
            else:
                st.error("JSON должен быть массивом объектов.")
    except Exception as e:
        st.error(f"Ошибка при загрузке: {e}")
    return None

def generate_pdf_report(df, report_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, "AI Отчет о данных:\n")
    pdf.multi_cell(0, 10, report_text)
    buffer = io.BytesIO()
    pdf.output(buffer)
    buffer.seek(0)
    return buffer

uploaded_file = st.file_uploader("Загрузите файл", type=["csv", "xlsx", "xls", "json"])

if uploaded_file:
    df = load_data(uploaded_file)
    if df is not None:
        st.success(f"Загружено {df.shape[0]} строк, {df.shape[1]} колонок")

        tab1, tab2, tab3, tab4 = st.tabs(["🧾 Данные", "📊 Визуализация", "🧠 AI-Анализ", "📄 PDF Отчет"])

        with tab1:
            st.dataframe(df.head())

        with tab2:
            num_cols = df.select_dtypes(include='number').columns
            cat_cols = df.select_dtypes(include='object').columns

            if num_cols.any():
                col = st.selectbox("Выберите числовую колонку", num_cols)
                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
                sns.histplot(df[col], kde=True, ax=ax1)
                sns.boxplot(x=df[col], ax=ax2)
                ax1.set_title("Гистограмма")
                ax2.set_title("Boxplot")
                st.pyplot(fig)

            if cat_cols.any():
                col = st.selectbox("Выберите категориальную колонку", cat_cols)
                fig, ax = plt.subplots()
                df[col].value_counts().plot(kind='bar', ax=ax)
                ax.set_title("Распределение категорий")
                st.pyplot(fig)

        with tab3:
            st.write("🔬 Попробуем обучить модель классификации...")

            target = st.selectbox("Выберите целевую переменную (классификация)", df.columns)
            features = st.multiselect("Выберите числовые признаки", df.select_dtypes('number').drop(columns=[target], errors='ignore').columns)

            if features and target:
                try:
                    X = df[features]
                    y = df[target]
                    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
                    model = RandomForestClassifier()
                    model.fit(X_train, y_train)
                    y_pred = model.predict(X_test)
                    report = classification_report(y_test, y_pred)
                    st.code(report)
                except Exception as e:
                    st.error(f"Ошибка: {e}")
            else:
                st.info("Выберите целевую переменную и признаки.")

        with tab4:
            st.write("📄 Сгенерировать PDF отчет")
            report_summary = f"Форма данных: {df.shape}\nКолонки: {list(df.columns)}\n\n"
            if 'report' in locals():
                report_summary += "\nКлассификационный отчет:\n" + report
            pdf = generate_pdf_report(df, report_summary)
            st.download_button("📥 Скачать отчет PDF", pdf, file_name="data_report.pdf")

else:
    st.info("Загрузите файл для начала анализа.")