# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJdafPVAxfcDEkAfmrep7J3Lrhx3KF5d
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json

st.set_page_config(page_title="📊 AI Визуализатор Данных", layout="wide")
st.title("📊 AI-помощник для визуализации данных")
st.markdown("Загрузите файл (CSV, Excel или JSON) — и получите автоматический анализ + графики.")

def load_data(uploaded_file):
    try:
        if uploaded_file.name.endswith('.csv'):
            return pd.read_csv(uploaded_file)
        elif uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        elif uploaded_file.name.endswith('.json'):
            data = json.load(uploaded_file)
            if isinstance(data, list):
                return pd.DataFrame(data)
            else:
                st.error("JSON должен содержать массив объектов.")
                return None
        else:
            st.error("Неподдерживаемый формат файла")
            return None
    except Exception as e:
        st.error(f"Ошибка при загрузке файла: {e}")
        return None

uploaded_file = st.file_uploader("Загрузите файл", type=["csv", "xlsx", "xls", "json"])

if uploaded_file:
    df = load_data(uploaded_file)
    if df is not None:
        st.subheader("🔍 Общая информация")
        st.write(f"Строк: {df.shape[0]}, Колонок: {df.shape[1]}")

        tab1, tab2, tab3 = st.tabs(["Данные", "Статистика", "Визуализация"])

        with tab1:
            st.dataframe(df.head())

        with tab2:
            st.write("Типы данных:")
            st.write(df.dtypes)
            st.write("Пропущенные значения:")
            st.write(df.isnull().sum())

        with tab3:
            num_cols = df.select_dtypes(include=["number"]).columns
            if len(num_cols) > 0:
                selected_num = st.selectbox("Выберите числовую колонку", num_cols)
                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
                sns.histplot(df[selected_num], ax=ax1, kde=True)
                sns.boxplot(x=df[selected_num], ax=ax2)
                st.pyplot(fig)

            cat_cols = df.select_dtypes(include=["object", "category"]).columns
            if len(cat_cols) > 0:
                selected_cat = st.selectbox("Выберите категориальную колонку", cat_cols)
                fig, ax = plt.subplots()
                df[selected_cat].value_counts().plot(kind='bar', ax=ax)
                st.pyplot(fig)
else:
    st.info("Пожалуйста, загрузите файл для анализа")